### ISSUE TITLE
pdd command throws segmentation fault

### ISSUE THREAD

**Issue by Diveshmahajan4** [wargio/r2dec-js#334]
**Describe the bug**
Whenever I try to run `pdd` command I get a ` Segmentation fault (core dumped) ` error.
I tried uninstalling and reinstalling r2dec and radare2 but still face the same error.
I am using this setup in a docker container with radare2 5.9.5 32693 @ linux-x86-64 

**Component**
- [x] x86-64

![image](https://github.com/user-attachments/assets/1bfb94f5-2ba5-48e8-bb2c-5e2f360f4bc0)

**Comment by trufae** [comment]
Should be fixed with the code in git, please update r2 and rebuild r2dec from git too and confirm

**Comment by Diveshmahajan4** [comment]
Nope, still the same error.
radare2 updated to 5.9.7 and reinstalled r2dec

**Comment by Diveshmahajan4** [comment]
Great! It works, I guess the recent PR  fixes this issue.
Can I know what was the issue ?

**Comment by wargio** [comment]
r2 includes qjs and also r2dec did, so there was a mismatch on the symbols which caused to crash
